version: '3.8'

services:
  postgresql:
    image: postgres:14.2
    environment:
      POSTGRES_DB: confdb
      POSTGRES_USER: confdb
      POSTGRES_PASSWORD: confdb
    ports:
      - '5432:5432'
    volumes:
      - 'pgdataconf:/var/lib/postgresql/data'
    networks:
      confnetwork:
        ipv4_address: 10.0.0.4

  confluence-server:
    depends_on:
      - postgresql
    image: atlassian/confluence:7.17.1
    ports:
      - '8090:8090'
      - '8091:8091'
    volumes:
      - 'conf-home:/var/atlassian/application-data/confluence'
    environment:
      ATL_JDBC_URL: jdbc:postgresql://10.0.0.4:5432/confdb
      ATL_JDBC_USER: confdb
      ATL_JDBC_PASSWORD: confdb
      ATL_DB_TYPE: postgresql
      ATL_DB_DRIVER: org.postgresql.Driver
      ATL_DB_SCHEMA_NAME: public
    networks:
      confnetwork:
        ipv4_address: 10.0.0.5

volumes:
  pgdataconf: {}
  conf-home: {}

networks:
  confnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24