version: '3.8'
networks:
  sonarNet:
    name: "sonarNet"

services:
  sonarqube:
    image: sonarqube:8.9.7-community
    restart: unless-stopped
    container_name: sonarqube
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarpass
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    ports:
      - '9000:9000'
      - '9092:9092'
    volumes:
      - sonar-conf:/opt/sonarqube/conf
      - sonar-data:/opt/sonarqube/data
      - sonar-extensions:/opt/sonarqube/extensions
      - sonar-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - "sonarNet"

  db:
    image: postgres:13.6
    restart: unless-stopped
    container_name: sonarqube-db
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarpass
      - POSTGRES_DB=sonarqube
    volumes:
      - sonar-db:/var/lib/postgresql
      - sonar-db-data:/var/lib/postgresql/data
    networks:
      - "sonarNet"

volumes:
  sonar-conf:
  sonar-data:
  sonar-extensions:
  sonar-plugins:
  sonar-db:
  sonar-db-data: