version: '3.8'
networks:
  gitlab:
    name: 'gitlab'

services:
  web:
    image: gitlab/gitlab-ce:14.9.3-ce.0
    container_name: gitlab-ce
    restart: on-failure
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - gitlab-conf:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    networks:
      - 'gitlab'

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine-v14.9.1
    container_name: gitlab-runner
    restart: on-failure
    depends_on:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner:/etc/gitlab-runner
    networks:
      - 'gitlab'

volumes:
  gitlab-conf:
  gitlab-logs:
  gitlab-data:
  gitlab-runner:
