version: '3.8'
networks:
  flinkNet:
    name: "flinkNet"
    driver: bridge

services:
  jobmanager:
    image: flink:1.14.4-scala_2.12-java11
    container_name: jobmanager
    restart: on-failure
    expose:
      - '6123'
    ports:
      - '7081:8081'
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - "flinkNet"

  taskmanager:
    image: flink:1.14.4-scala_2.12-java11
    container_name: taskmanager
    restart: on-failure
    expose:
      - '6121'
      - '6122'
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - 'jobmanager:jobmanager'
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - "flinkNet"